Dark mode (re)
fdamken/summaries pull request #15
Opened 2022-09-02 19:58 UTC by Rdeisenroth

Dieser PR ermöglicht dark mode Unterstützungen für alle Zusammenfassungen durch mein [darkmode](https://www.ctan.org/pkg/darkmode)-Paket.

Aktueller Status: 
- [x] Anpassung von /pkg
- [ ] TeX-Anpassung der einzelnen Zusammenfassungen
- [ ] Grafiken für den Darkmode invertieren
- [x] Dark mode aktivierbar per Umgebungsvariable `DARK_MODE=1`
- [x] Automatisches Auswählen des Invertierten TU-Logos, falls existent (darf nicht mitgeliefert werden, wegen copyright)
- [x] Build-Section im readme angepasst

2022-09-06 21:05 UTC, Rdeisenroth reviewed
Hier noch ein Paar Anmerkungen:

2022-09-06 21:05 UTC, Rdeisenroth commented on pkg/fdsummary.cls
> +\ifLuaTeX
Ohne dass kann man **keine** Zusammenfassung mit LuaTeX kompillieren

2022-09-06 21:05 UTC, Rdeisenroth commented on summaries/cs/elective/vc/statml/darkmodeify-pdfs.sh
> +for f in tmp-*.pdf; do
hier könnte man theoretisch noch verhindern, dass mehrfaches ausführen zu fehlern führt durch sowas wie
```diff
- for f in tmp-*.pdf; do
+ for f in tmp-*[!-dark].pdf; do

2022-09-16 17:34 UTC, Rdeisenroth commented on .github/workflows/publish-all.yml
> +          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
Passt jetzt

2022-10-18 17:09 UTC, fdamken requested changes

2022-10-18 17:09 UTC, fdamken commented on summaries/cs/elective/vc/ivva/content.tex
> +					\includegraphics[width=0.8\linewidth]{glyphen-dark}
Wieso nicht mit dem `if`?

2022-10-18 17:09 UTC, fdamken commented on summaries/cs/elective/vc/ivva/content.tex
> +					\includegraphics[width=0.8\linewidth]{glyphen-dark}
Auch im Rest der Datei.

2022-10-18 17:09 UTC, fdamken commented on pkg/fdsummary.cls
> +\newcommand{\includeinvertablegraphics}[2][]{% Grafik wird beim Dark Mode automatisch Invertiert (rgb)
ok

2022-10-18 17:09 UTC, fdamken commented on README.md
> +- If you want to enable dark-Mode, set `DARK_MODE=1` before executing the script
ok

2022-10-18 19:20 UTC, fdamken approved these changes

2022-10-18 19:35 UTC, merged